package server

import (
	"encoding/json"
	"eosApi/httpPost"
)

func GetBlockInfo(blockNum int)  string{
	type AutoGenerated struct {
		BlockNumOrID int `json:"block_num_or_id"`
	}
	block_num_0:=AutoGenerated{
		blockNum,
	}
	block_num_1,_:=json.Marshal(block_num_0)
	block_num :=string(block_num_1)

	//获取返回信息
	body :=httpPost.HttpPost(block_num,"chain","get_block")

	//fmt.Println(string(body))
	return string(body)
}
