package server

import (
	"encoding/json"
	"eosApi/httpPost"
	"fmt"
)

func GetBlock()(string,int,int){


	HeadBlockNum:=GetInfo()
	type AutoGenerated struct {
		BlockNumOrID int `json:"block_num_or_id"`
	}

	block_num_0:=AutoGenerated{
		HeadBlockNum,
	}

	block_num_1,_:=json.Marshal(block_num_0)
	block_num :=string(block_num_1)

	//fmt.Println("HeadBlockNum",HeadBlockNum)

	//获取返回信息
	body :=httpPost.HttpPost(block_num,"chain","get_block")

	fmt.Println("getblock返回信息：",string(body))

	type getblock_0 struct {
		Timestamp         string        `json:"timestamp"`
		Producer          string        `json:"producer"`
		Confirmed         int           `json:"confirmed"`
		Previous          string        `json:"previous"`
		TransactionMroot  string        `json:"transaction_mroot"`
		ActionMroot       string        `json:"action_mroot"`
		ScheduleVersion   int           `json:"schedule_version"`
		NewProducers      interface{}   `json:"new_producers"`
		HeaderExtensions  []interface{} `json:"header_extensions"`
		ProducerSignature string        `json:"producer_signature"`
		Transactions      []interface{} `json:"transactions"`
		BlockExtensions   []interface{} `json:"block_extensions"`
		ID                string        `json:"id"`
		BlockNum          int           `json:"block_num"`
		RefBlockPrefix    int           `json:"ref_block_prefix"`
	}

	var getblock getblock_0
	json.Unmarshal(body,&getblock)

	return getblock.Timestamp,getblock.RefBlockPrefix,HeadBlockNum


}
