package server

import (
	"encoding/json"
	"eosApi/httpPost"
	"fmt"
)

func GetInfo() (int){
	body:=httpPost.HttpPost("","chain","get_info")
	fmt.Println("getinfo返回信息：",string(body))

	type AutoGenerated struct {
		ServerVersion            string `json:"server_version"`
		ChainID                  string `json:"chain_id"`
		HeadBlockNum             int    `json:"head_block_num"`
		LastIrreversibleBlockNum int    `json:"last_irreversible_block_num"`
		LastIrreversibleBlockID  string `json:"last_irreversible_block_id"`
		HeadBlockID              string `json:"head_block_id"`
		HeadBlockTime            string `json:"head_block_time"`
		HeadBlockProducer        string `json:"head_block_producer"`
		VirtualBlockCPULimit     int    `json:"virtual_block_cpu_limit"`
		VirtualBlockNetLimit     int    `json:"virtual_block_net_limit"`
		BlockCPULimit            int    `json:"block_cpu_limit"`
		BlockNetLimit            int    `json:"block_net_limit"`
		ServerVersionString      string `json:"server_version_string"`
		ForkDbHeadBlockNum       int    `json:"fork_db_head_block_num"`
		ForkDbHeadBlockID        string `json:"fork_db_head_block_id"`
	}

	var getinfo AutoGenerated
	json.Unmarshal(body,&getinfo)
	//fmt.Println(getinfo.ChainID,getinfo.HeadBlockNum)
	return getinfo.HeadBlockNum


}
